mots = [
    "pomme", "banane", "orange", "fraises", "cerise", "ananas", "poire", "raisin", "abricot", "mandarine",
    "pasteque", "framboise", "chocolat", "caramel", "vanille", "chantilly", "pomme de terre", "concombre",
    "carotte", "brocoli", "poivron", "champignon", "ordinateur", "musique", "montagne", "restaurant", "universite",
    "professeur", "elephant", "crocodile", "requin", "baleine", "girafe", "souris", "chauve-souris", "grenouille",
    "hibou",
    "elephant", "lion", "tigre", "gazelle", "girafe", "crocodile", "requin", "chameau", "chimpanze", "leopard",
    "rhinoceros", "hippopotame", "kangourou", "alligator", "perroquet", "papillon", "dauphin", "ecureuil", "tortue",
    "ecureuil",
    "papillon", "dauphin", "tortue", "ornithorynque", "aigle", "chouette", "ecureuil", "girafe", "elephant",
    "kangourou",
    "sauterelle", "coccinelle", "ecureuil", "grenouille", "tortue", "crocodile", "hippopotame", "leopard", "chimpanze",
    "kangourou",
    "alligator", "perroquet", "papillon", "dauphin", "rhinoceros", "gazelle", "chouette", "ornithorynque", "perroquet",
    "rhinoceros",
    "crocodile", "chimpanze", "tortue", "girafe", "alligator", "hippopotame", "leopard", "grenouille", "sauterelle",
    "gazelle",
    "rhinoceros", "chouette", "ornithorynque", "kangourou", "dauphin", "perroquet", "papillon", "ecureuil", "tortue",
    "rhinoceros",
    "alligator", "sauterelle", "chimpanze", "kangourou", "crocodile", "gazelle", "ornithorynque", "tortue",
    "hippopotame", "sauterelle",
    "dauphin", "papillon", "chouette", "ecureuil", "grenouille", "leopard", "girafe", "elephant", "ornithorynque",
    "aigle", "chimpanze",
    "alligator", "sauterelle", "gazelle", "chouette", "hippopotame", "perroquet", "rhinoceros", "papillon", "tortue",
    "crocodile",
    "dauphin", "ecureuil", "kangourou", "grenouille", "leopard", "elephant", "chimpanze", "girafe", "chouette",
    "ornithorynque",
    "rhinoceros", "sauterelle", "gazelle", "hippopotame", "perroquet", "alligator", "papillon", "tortue", "kangourou",
    "dauphin",
    "crocodile", "chimpanze", "gazelle", "rhinoceros", "tortue", "hippopotame", "sauterelle", "chouette",
    "ornithorynque", "alligator",
    "kangourou", "dauphin", "papillon", "perroquet", "ecureuil", "tortue", "crocodile", "girafe", "grenouille",
    "hippopotame",
    "elephant", "leopard", "chimpanze", "chouette", "rhinoceros", "ornithorynque", "aigle", "papillon", "tortue",
    "sauterelle",
    "gazelle", "kangourou", "dauphin", "perroquet", "ecureuil", "hippopotame", "sauterelle", "ornithorynque", "tortue",
    "chimpanze",
    "chouette", "crocodile", "gazelle", "grenouille", "sauterelle", "papillon", "rhinoceros", "alligator", "kangourou",
    "perroquet",
    "ecureuil", "aigle", "chimpanze", "chouette", "crocodile", "sauterelle", "gazelle", "ornithorynque", "hippopotame",
    "kangourou",
    "dauphin", "papillon", "perroquet", "tortue", "rhinoceros", "alligator", "ecureuil", "chimpanze", "chouette",
    "gazelle", "sauterelle",
    "grenouille", "hippopotame", "ornithorynque", "papillon", "rhinoceros", "tortue", "kangourou", "crocodile",
    "dauphin", "ecureuil", "girafe",
    "grenouille", "hippopotame", "leopard", "elephant", "chimpanze", "gazelle", "chouette", "ornithorynque", "aigle",
    "crocodile", "sauterelle",
    "rhinoceros", "tortue", "hippopotame", "sauterelle", "chouette", "ornithorynque", "alligator", "kangourou",
    "dauphin", "perroquet", "papillon",
    "tortue", "crocodile", "gazelle", "rhinoceros", "chimpanze", "kangourou", "tortue", "hippopotame", "sauterelle",
    "dauphin", "papillon",
    "chouette", "ecureuil", "grenouille", "leopard", "girafe", "elephant", "ornithorynque", "aigle", "chimpanze",
    "alligator", "sauterelle",
]